<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 svelte/static/card.glb
-->

<script>
  import { Group } from 'three'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/card.glb')

</script>

<T is={ref} dispose={false} {...$$restProps}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Cube.geometry} material={gltf.materials['Material.001']} castShadow/>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
